### ISSUE TITLE
Add "How to Play" section

### ISSUE THREAD

**Issue by DevWarr** [Robot-Versus-Zombies/front-end#39]
## Issue Outline 
For users who have played games before, it can be easy to understand the "WASD to move, space or click to interact" style controls.

However, for new users who aren't used to playing games (and just in general) it can be helpful to have the controls listed somewhere on the screen so users know how to play.

## References
Here are some links to other games that have the controls beneath the game - maybe Robots vs Zombies could use a similar style?
* https://flowt.itch.io/kingdom-hearts-1975
* https://flowt.itch.io/virtua-runner

**Comment by JossWritesCode** [comment]
Great idea. I honestly haven't been thinking about the new user experience as much as I should be
